from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
old='''          navContainer.innerHTML = `<!-- ABEL_TRAINER_NAV_V3 --><a href="./trainer.html" class="flex items-center gap-2 px-4 py-3 text-xs tracking-[0.12em] whitespace-nowrap text-[#47E6FF] hover:text-white transition-colors shrink-0" title="Trainer"><span aria-hidden="true">⚡</span><span>TRAINER</span></a>` + TABS.map(t => {\n            const active = t.id === state.currentTab;\n            return `\n              <button onclick="window.switchTab('${t.id}')" class="relative flex items-center gap-2 px-4 py-3 text-xs uppercase tracking-widest font-semibold transition-colors whitespace-nowrap snap-start shrink-0" style="color: ${active ? t.accent : "#8A8F98"}">\n                <i data-lucide="${t.icon}" class="w-4 h-4"></i>\n                <span>${t.label}</span>\n                ${active ? `<span class="absolute left-2 right-2 -bottom-px h-[3px] rounded-full" style="background: ${t.accent}"></span>` : ""}\n              </button>\n            `;\n          }).join("");'''
new='''          const trainerNav = `<a href="./trainer.html" class="flex items-center gap-2 px-4 py-3 text-xs tracking-[0.12em] whitespace-nowrap text-[#47E6FF] hover:text-white transition-colors shrink-0" title="Trainer"><span aria-hidden="true">⚡</span><span>TRAINER</span></a>`;\n          navContainer.innerHTML = TABS.map(t => {\n            const active = t.id === state.currentTab;\n            const tabButton = `\n              <button onclick="window.switchTab('${t.id}')" class="relative flex items-center gap-2 px-4 py-3 text-xs uppercase tracking-widest font-semibold transition-colors whitespace-nowrap snap-start shrink-0" style="color: ${active ? t.accent : "#8A8F98"}">\n                <i data-lucide="${t.icon}" class="w-4 h-4"></i>\n                <span>${t.label}</span>\n                ${active ? `<span class="absolute left-2 right-2 -bottom-px h-[3px] rounded-full" style="background: ${t.accent}"></span>` : ""}\n              </button>\n            `;\n            const isAgenda = t.id === "agenda" || /AGENDA/i.test(t.label || "");\n            return tabButton + (isAgenda ? trainerNav : "");\n          }).join("");'''
if old not in s:
    raise SystemExit('Bloco atual de navegação não encontrado')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('Trainer posicionado logo após Agenda & Plantões')
